name: "PODCAST GENERATOR"
author: "Ray Villalobos"
description: "Generate a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commitor's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commitor's name
    required: true
    default: ${{ github.actor }}